export const BULK_EMPLOYEE_TEMPLATE_HEADERS = [
  'Employee Roll No.',
  'Name of the employee',
  'Email',
  'Mobile',
  'Place of Posting',
  'Designation',
  'Department',
  'Manager',
  'Training Department Officer (CTD)',
  'OSD Officer',
  'Reporting Manager Email',
  'Skip Level 1 Manager Email',
  'Skip Level 2 Manager Email',
];

export const BULK_EMPLOYEE_SAMPLE_ROWS = [
  [
    'E1001',
    'Arjun Mehta',
    'arjun@corp.in',
    '9876543210',
    'Mumbai',
    'Analyst',
    'Finance',
    'No',
    'No',
    'No',
    'manager@corp.in',
    '',
    '',
  ],
  [
    'E1002',
    'Sara Iyer',
    'sara@corp.in',
    '9876543211',
    'Delhi',
    'Senior Analyst',
    'Finance',
    'Yes',
    'No',
    'No',
    'manager@corp.in',
    'skiplevel1@corp.in',
    '',
  ],
];
